<?php

namespace App\Exceptions;

use Illuminate\Auth\AuthenticationException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Validation\ValidationException;
use Throwable;

use function response;
use function var_dump;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        if ($e instanceof ValidationException) {
            throw new HttpResponseException(
                response()->json(
                    [
                        'success' => false,
                        'message' => 'Validation errors',
                        'data' => $e->errors(),
                    ],
                    422
                )
            );
        }

        if ($e instanceof AuthenticationException) {
            throw new HttpResponseException(
                response()->json(
                    [
                        'success' => false,
                        'message' => $e->getMessage(),
                    ],
                    401
                )
            );
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
